-- MySQL Script generated by MySQL Workbench
-- Wed Jun 24 17:41:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fields
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fields` ;

-- -----------------------------------------------------
-- Schema fields
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fields` DEFAULT CHARACTER SET utf8 ;
USE `fields` ;

-- -----------------------------------------------------
-- Table `fields`.`sizes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fields`.`sizes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `size` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fields`.`colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fields`.`colors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fields`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fields`.`product_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fields`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fields`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` INT NOT NULL,
  `stock` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `size_id` INT NOT NULL,
  `color_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `description` VARCHAR(100) NULL,
  `image` TEXT(100) NULL,
  `highlighted` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `category_id`, `color_id`, `size_id`),
  INDEX `fk_products_size1_idx` (`size_id` ASC) ,
  INDEX `fk_products_color1_idx` (`color_id` ASC) ,
  INDEX `fk_products_category1_idx` (`category_id` ASC) ,
  CONSTRAINT `fk_products_size1`
    FOREIGN KEY (`size_id`)
    REFERENCES `fields`.`sizes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `fields`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `fields`.`product_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fields`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fields`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fields`.`user_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fields`.`user_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fields`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fields`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NULL,
  `password` VARCHAR(200) NOT NULL,
  `avatar` TEXT(100) NULL,
  `cart_id` INT NOT NULL,
  `phone` INT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`, `category_id`, `cart_id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) ,
  INDEX `fk_Users_cart1_idx` (`cart_id` ASC) ,
  INDEX `fk_users_user_category1_idx` (`category_id` ASC) ,
  CONSTRAINT `fk_Users_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `fields`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_user_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `fields`.`user_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fields`.`product_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fields`.`product_cart` (
  `product_id` INT NOT NULL,
  `cart_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`, `product_id`, `cart_id`),
  INDEX `fk_Products_has_cart_cart1_idx` (`cart_id` ASC) ,
  INDEX `fk_Products_has_cart_Products1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_Products_has_cart_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `fields`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_has_cart_cart1`
    FOREIGN KEY (`cart_id`)
    REFERENCES `fields`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
